# Generated by Django 4.2.3 on 2023-09-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiblog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=255),
        ),
    ]
